---
title: "PFMproj-main"
author: "Zoe Zhou"
date: "10/12/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


10/12/2019 

This data set is RAW data from subjects(physios) doing certain exercises
||||||||||||||||||||||||||||||||Might need some cleaning|||||||||||||||||||||||||||||||||||||||

----------------------------------------- TASK -----------------------------------------------
We are looking for the peak pressure values among three contractions, to find which one or more than one sensors representing the active pelvic muscles. We are particularly interested in the variability of the result.

***************************************** Note *********************************************
--Each pressure measurement includes the __baseline atmosphere pressure__ due to the great sensitivity of the sensors. We might or might not need to exclude this baseline value during the investigation. Currently we are taking the value right (within 3-5 seconds) before each contraction to be treated as the initial pressure value. 
--All the timestamps for contractions and rest, are recorded manually by the user, saved in JSON files. 

~~ Pressure values are records at a frequency of 50 Hz. ~~
~~ So 50 measurements per second. ~~
~~ 1 measurement every 20 milliseconds.  ~~


11/12/2019 Corrected: We were using device _pfd0084_ which records measurements at a frequency of  __100 Hz__. 
So we have 100 measurements per second. 1 measurement every 10 milliseconds. 


***
##### Finding baseline: Rough Guess

As each sensor has a different initial pressure value at the start of the pfmc exercise, the patterns of pressure changes are not so easy-to-understand. Hence we should remove the baseline pressure values and focus on the changes. Then we can get a better idea of which sensor has the greatest change.

General Method:
Find a rest period of at least 2 seconds with relatively stable pressure values, average it out for each sensor and treat it as the baseline.

Question:
How to find this *stable rest period*?

Procedure:
We attempted 3 times taking 3 different rest periods. 
Attemp1: Take the first exercise, relax 30 seconds. 

Attempt2: Take all the time before the first contraction. Means when the device started recording, we get rest data, until the subject start to contract.

Attempt3: Take the 15s rest time within the pfmc exercise. 

After taking out the average pressure values for each sensor, all these 3 trials gave very similar output. Regarding to the negative values, they can be explained by the sucction of the sensor member, resulting the pressure decrease.

However, the 3rd attempt gave the most reliable initial value(closest to 0), so we will be using this approach for all subjects.

----------See R code from [s0007.Rmd] ("C:/Users/Pluie/Desktop/SS research/ssResearch/7542a8d335c2d356_7_csv/s0007/s0007.rmd")


##### Now call the big nice function and check out the graphic results
```{r}
# Find folders that contain our data
data_folders = list.files(pattern = "_csv")

# Load in all the helper functions
source("Functions.R")

# Get all pfmc data
pfmcdatalist = lapply(data_folders, process)

# Extract out baseline removed data (aka pfmcchange data) from all 3 participants
pfmcchange.df.list = list()
for (i in 1:length(pfmcdatalist)) {
  pfmcchange.df.list[[i]] = pfmcdatalist[[i]][[4]]
  names(pfmcchange.df.list)[i] = names(pfmcdatalist[[i]])[4]
}
```

### Visualize our data
```{r}
# Initialize empty lists to store all pfmc plots
change.plots = list()
pressure.plots = list()

# Get the plots
for (i in (1:length(pfmcdatalist))) {
  pressure.plot.name = as.character(names(pfmcdatalist[[i]])[3])
  change.plot.name = as.character(names(pfmcdatalist[[i]])[4])
  
  pressure.plots[[i]] = myplot(pfmcdatalist[[i]][[3]], name = pressure.plot.name)
  
  names(pressure.plots)[[i]] = pressure.plot.name
  
  change.plots[[i]] = myplot(pfmcdatalist[[i]][[4]], name = change.plot.name)
  
  names(change.plots)[[i]] = change.plot.name
}

# Look at the plots
print(change.plots)
print(pressure.plots)
```


```{r eval = FALSE}
# Save the plots
# invisible(mapply(ggsave, width = 10, height = 4, dpi = 300,
#                  file = paste0(names(change.plots), ".png"), plot = change.plots))

```


